export const distressQuotes = {
  low: [
    "You're doing well. Keep going 🌱",
    "Small steps forward still matter.",
    "Peace looks good on you.",
    "You're stronger than you think.",
    "Keep nurturing your calm.",
    "You’re building something meaningful.",
    "Your consistency is powerful.",
    "You deserve this stability.",
    "Growth is happening quietly.",
    "Stay grounded, you're doing great.",
    "You're in control of your pace.",
    "Calm minds create strong futures.",
    "You’ve come far already.",
    "Your effort is enough.",
    "Balance looks good on you.",
    "You’re becoming your best self."
  ],

  medium: [
    "Take a breath. You’ve got this 💙",
    "It's okay to not have everything figured out.",
    "One step at a time.",
    "Pause. Reset. Continue.",
    "You’re allowed to feel this.",
    "You’re not behind in life.",
    "Give yourself some grace today.",
    "Rest is productive too.",
    "You don’t have to rush healing.",
    "It’s okay to slow down.",
    "You’re doing better than you think.",
    "Storms don’t last forever.",
    "You are learning and growing.",
    "Take things moment by moment.",
    "You are not alone in this.",
    "Progress is still progress."
  ],

  high: [
    "Hey… it’s okay. You’re safe here 🤍",
    "You don’t have to carry everything alone.",
    "Take a deep breath with me.",
    "This moment will pass.",
    "You matter more than you think.",
    "You are not your thoughts.",
    "It's okay to ask for help.",
    "You’re stronger than this feeling.",
    "Let’s take it one breath at a time.",
    "You’re not broken.",
    "Your feelings are valid.",
    "You deserve kindness — especially from yourself.",
    "Even this will pass.",
    "You are not alone right now.",
    "Stay. Breathe. You're okay.",
    "You're safe. I'm here with you.",
    "You don’t need to solve everything right now.",
    "Just get through this minute.",
  ]
};